// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorResp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ErrorResp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ErrorResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ErrorResp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ErrorResp_2eproto() {
  protobuf_AddDesc_ErrorResp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ErrorResp.proto");
  GOOGLE_CHECK(file != NULL);
  ErrorResp_descriptor_ = file->message_type(0);
  static const int ErrorResp_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorResp, errorcode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorResp, extrainfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorResp, errordescription_),
  };
  ErrorResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ErrorResp_descriptor_,
      ErrorResp::default_instance_,
      ErrorResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ErrorResp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ErrorResp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ErrorResp_descriptor_, &ErrorResp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ErrorResp_2eproto() {
  delete ErrorResp::default_instance_;
  delete ErrorResp_reflection_;
}

void protobuf_AddDesc_ErrorResp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017ErrorResp.proto\"K\n\tErrorResp\022\021\n\terrorC"
    "ode\030\001 \001(\005\022\021\n\tExtraInfo\030\002 \001(\r\022\030\n\020errorDes"
    "cription\030\003 \001(\t", 94);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ErrorResp.proto", &protobuf_RegisterTypes);
  ErrorResp::default_instance_ = new ErrorResp();
  ErrorResp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ErrorResp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ErrorResp_2eproto {
  StaticDescriptorInitializer_ErrorResp_2eproto() {
    protobuf_AddDesc_ErrorResp_2eproto();
  }
} static_descriptor_initializer_ErrorResp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ErrorResp::kErrorCodeFieldNumber;
const int ErrorResp::kExtraInfoFieldNumber;
const int ErrorResp::kErrorDescriptionFieldNumber;
#endif  // !_MSC_VER

ErrorResp::ErrorResp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ErrorResp)
}

void ErrorResp::InitAsDefaultInstance() {
}

ErrorResp::ErrorResp(const ErrorResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ErrorResp)
}

void ErrorResp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  errorcode_ = 0;
  extrainfo_ = 0u;
  errordescription_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ErrorResp::~ErrorResp() {
  // @@protoc_insertion_point(destructor:ErrorResp)
  SharedDtor();
}

void ErrorResp::SharedDtor() {
  if (errordescription_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete errordescription_;
  }
  if (this != default_instance_) {
  }
}

void ErrorResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ErrorResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ErrorResp_descriptor_;
}

const ErrorResp& ErrorResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ErrorResp_2eproto();
  return *default_instance_;
}

ErrorResp* ErrorResp::default_instance_ = NULL;

ErrorResp* ErrorResp::New() const {
  return new ErrorResp;
}

void ErrorResp::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ErrorResp*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(errorcode_, extrainfo_);
    if (has_errordescription()) {
      if (errordescription_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        errordescription_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ErrorResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ErrorResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 errorCode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &errorcode_)));
          set_has_errorcode();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_ExtraInfo;
        break;
      }

      // optional uint32 ExtraInfo = 2;
      case 2: {
        if (tag == 16) {
         parse_ExtraInfo:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &extrainfo_)));
          set_has_extrainfo();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_errorDescription;
        break;
      }

      // optional string errorDescription = 3;
      case 3: {
        if (tag == 26) {
         parse_errorDescription:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_errordescription()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->errordescription().data(), this->errordescription().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "errordescription");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ErrorResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ErrorResp)
  return false;
#undef DO_
}

void ErrorResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ErrorResp)
  // optional int32 errorCode = 1;
  if (has_errorcode()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->errorcode(), output);
  }

  // optional uint32 ExtraInfo = 2;
  if (has_extrainfo()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->extrainfo(), output);
  }

  // optional string errorDescription = 3;
  if (has_errordescription()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->errordescription().data(), this->errordescription().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "errordescription");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->errordescription(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ErrorResp)
}

::google::protobuf::uint8* ErrorResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ErrorResp)
  // optional int32 errorCode = 1;
  if (has_errorcode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->errorcode(), target);
  }

  // optional uint32 ExtraInfo = 2;
  if (has_extrainfo()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->extrainfo(), target);
  }

  // optional string errorDescription = 3;
  if (has_errordescription()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->errordescription().data(), this->errordescription().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "errordescription");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->errordescription(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ErrorResp)
  return target;
}

int ErrorResp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 errorCode = 1;
    if (has_errorcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->errorcode());
    }

    // optional uint32 ExtraInfo = 2;
    if (has_extrainfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->extrainfo());
    }

    // optional string errorDescription = 3;
    if (has_errordescription()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->errordescription());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ErrorResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ErrorResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ErrorResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ErrorResp::MergeFrom(const ErrorResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_errorcode()) {
      set_errorcode(from.errorcode());
    }
    if (from.has_extrainfo()) {
      set_extrainfo(from.extrainfo());
    }
    if (from.has_errordescription()) {
      set_errordescription(from.errordescription());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ErrorResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ErrorResp::CopyFrom(const ErrorResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ErrorResp::IsInitialized() const {

  return true;
}

void ErrorResp::Swap(ErrorResp* other) {
  if (other != this) {
    std::swap(errorcode_, other->errorcode_);
    std::swap(extrainfo_, other->extrainfo_);
    std::swap(errordescription_, other->errordescription_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ErrorResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ErrorResp_descriptor_;
  metadata.reflection = ErrorResp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
