// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerListResp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PlayerListResp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PlayerListResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PlayerListResp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PlayerListResp_2eproto() {
  protobuf_AddDesc_PlayerListResp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PlayerListResp.proto");
  GOOGLE_CHECK(file != NULL);
  PlayerListResp_descriptor_ = file->message_type(0);
  static const int PlayerListResp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayerListResp, room_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayerListResp, player_list_),
  };
  PlayerListResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PlayerListResp_descriptor_,
      PlayerListResp::default_instance_,
      PlayerListResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayerListResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayerListResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PlayerListResp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PlayerListResp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PlayerListResp_descriptor_, &PlayerListResp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PlayerListResp_2eproto() {
  delete PlayerListResp::default_instance_;
  delete PlayerListResp_reflection_;
}

void protobuf_AddDesc_PlayerListResp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024PlayerListResp.proto\"7\n\016PlayerListResp"
    "\022\020\n\010room_key\030\001 \001(\t\022\023\n\013player_list\030\002 \003(\t", 79);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PlayerListResp.proto", &protobuf_RegisterTypes);
  PlayerListResp::default_instance_ = new PlayerListResp();
  PlayerListResp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PlayerListResp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PlayerListResp_2eproto {
  StaticDescriptorInitializer_PlayerListResp_2eproto() {
    protobuf_AddDesc_PlayerListResp_2eproto();
  }
} static_descriptor_initializer_PlayerListResp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PlayerListResp::kRoomKeyFieldNumber;
const int PlayerListResp::kPlayerListFieldNumber;
#endif  // !_MSC_VER

PlayerListResp::PlayerListResp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PlayerListResp)
}

void PlayerListResp::InitAsDefaultInstance() {
}

PlayerListResp::PlayerListResp(const PlayerListResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PlayerListResp)
}

void PlayerListResp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  room_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PlayerListResp::~PlayerListResp() {
  // @@protoc_insertion_point(destructor:PlayerListResp)
  SharedDtor();
}

void PlayerListResp::SharedDtor() {
  if (room_key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete room_key_;
  }
  if (this != default_instance_) {
  }
}

void PlayerListResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PlayerListResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PlayerListResp_descriptor_;
}

const PlayerListResp& PlayerListResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PlayerListResp_2eproto();
  return *default_instance_;
}

PlayerListResp* PlayerListResp::default_instance_ = NULL;

PlayerListResp* PlayerListResp::New() const {
  return new PlayerListResp;
}

void PlayerListResp::Clear() {
  if (has_room_key()) {
    if (room_key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      room_key_->clear();
    }
  }
  player_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PlayerListResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PlayerListResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string room_key = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_room_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->room_key().data(), this->room_key().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "room_key");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_player_list;
        break;
      }

      // repeated string player_list = 2;
      case 2: {
        if (tag == 18) {
         parse_player_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_player_list()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->player_list(this->player_list_size() - 1).data(),
            this->player_list(this->player_list_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "player_list");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_player_list;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PlayerListResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PlayerListResp)
  return false;
#undef DO_
}

void PlayerListResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PlayerListResp)
  // optional string room_key = 1;
  if (has_room_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->room_key().data(), this->room_key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "room_key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->room_key(), output);
  }

  // repeated string player_list = 2;
  for (int i = 0; i < this->player_list_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->player_list(i).data(), this->player_list(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "player_list");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->player_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PlayerListResp)
}

::google::protobuf::uint8* PlayerListResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PlayerListResp)
  // optional string room_key = 1;
  if (has_room_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->room_key().data(), this->room_key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "room_key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->room_key(), target);
  }

  // repeated string player_list = 2;
  for (int i = 0; i < this->player_list_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->player_list(i).data(), this->player_list(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "player_list");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->player_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlayerListResp)
  return target;
}

int PlayerListResp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string room_key = 1;
    if (has_room_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->room_key());
    }

  }
  // repeated string player_list = 2;
  total_size += 1 * this->player_list_size();
  for (int i = 0; i < this->player_list_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->player_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PlayerListResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PlayerListResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PlayerListResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PlayerListResp::MergeFrom(const PlayerListResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  player_list_.MergeFrom(from.player_list_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_room_key()) {
      set_room_key(from.room_key());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PlayerListResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlayerListResp::CopyFrom(const PlayerListResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerListResp::IsInitialized() const {

  return true;
}

void PlayerListResp::Swap(PlayerListResp* other) {
  if (other != this) {
    std::swap(room_key_, other->room_key_);
    player_list_.Swap(&other->player_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PlayerListResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PlayerListResp_descriptor_;
  metadata.reflection = PlayerListResp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
