// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoveShape.proto

#ifndef PROTOBUF_RemoveShape_2eproto__INCLUDED
#define PROTOBUF_RemoveShape_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RemoveShape_2eproto();
void protobuf_AssignDesc_RemoveShape_2eproto();
void protobuf_ShutdownFile_RemoveShape_2eproto();

class RemoveShape;

// ===================================================================

class RemoveShape : public ::google::protobuf::Message {
 public:
  RemoveShape();
  virtual ~RemoveShape();

  RemoveShape(const RemoveShape& from);

  inline RemoveShape& operator=(const RemoveShape& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RemoveShape& default_instance();

  void Swap(RemoveShape* other);

  // implements Message ----------------------------------------------

  RemoveShape* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RemoveShape& from);
  void MergeFrom(const RemoveShape& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string msgid = 1;
  inline bool has_msgid() const;
  inline void clear_msgid();
  static const int kMsgidFieldNumber = 1;
  inline const ::std::string& msgid() const;
  inline void set_msgid(const ::std::string& value);
  inline void set_msgid(const char* value);
  inline void set_msgid(const char* value, size_t size);
  inline ::std::string* mutable_msgid();
  inline ::std::string* release_msgid();
  inline void set_allocated_msgid(::std::string* msgid);

  // optional uint32 shapeID = 2;
  inline bool has_shapeid() const;
  inline void clear_shapeid();
  static const int kShapeIDFieldNumber = 2;
  inline ::google::protobuf::uint32 shapeid() const;
  inline void set_shapeid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:RemoveShape)
 private:
  inline void set_has_msgid();
  inline void clear_has_msgid();
  inline void set_has_shapeid();
  inline void clear_has_shapeid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* msgid_;
  ::google::protobuf::uint32 shapeid_;
  friend void  protobuf_AddDesc_RemoveShape_2eproto();
  friend void protobuf_AssignDesc_RemoveShape_2eproto();
  friend void protobuf_ShutdownFile_RemoveShape_2eproto();

  void InitAsDefaultInstance();
  static RemoveShape* default_instance_;
};
// ===================================================================


// ===================================================================

// RemoveShape

// optional string msgid = 1;
inline bool RemoveShape::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RemoveShape::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RemoveShape::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RemoveShape::clear_msgid() {
  if (msgid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msgid_->clear();
  }
  clear_has_msgid();
}
inline const ::std::string& RemoveShape::msgid() const {
  // @@protoc_insertion_point(field_get:RemoveShape.msgid)
  return *msgid_;
}
inline void RemoveShape::set_msgid(const ::std::string& value) {
  set_has_msgid();
  if (msgid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msgid_ = new ::std::string;
  }
  msgid_->assign(value);
  // @@protoc_insertion_point(field_set:RemoveShape.msgid)
}
inline void RemoveShape::set_msgid(const char* value) {
  set_has_msgid();
  if (msgid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msgid_ = new ::std::string;
  }
  msgid_->assign(value);
  // @@protoc_insertion_point(field_set_char:RemoveShape.msgid)
}
inline void RemoveShape::set_msgid(const char* value, size_t size) {
  set_has_msgid();
  if (msgid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msgid_ = new ::std::string;
  }
  msgid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:RemoveShape.msgid)
}
inline ::std::string* RemoveShape::mutable_msgid() {
  set_has_msgid();
  if (msgid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msgid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:RemoveShape.msgid)
  return msgid_;
}
inline ::std::string* RemoveShape::release_msgid() {
  clear_has_msgid();
  if (msgid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = msgid_;
    msgid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RemoveShape::set_allocated_msgid(::std::string* msgid) {
  if (msgid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msgid_;
  }
  if (msgid) {
    set_has_msgid();
    msgid_ = msgid;
  } else {
    clear_has_msgid();
    msgid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:RemoveShape.msgid)
}

// optional uint32 shapeID = 2;
inline bool RemoveShape::has_shapeid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RemoveShape::set_has_shapeid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RemoveShape::clear_has_shapeid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RemoveShape::clear_shapeid() {
  shapeid_ = 0u;
  clear_has_shapeid();
}
inline ::google::protobuf::uint32 RemoveShape::shapeid() const {
  // @@protoc_insertion_point(field_get:RemoveShape.shapeID)
  return shapeid_;
}
inline void RemoveShape::set_shapeid(::google::protobuf::uint32 value) {
  set_has_shapeid();
  shapeid_ = value;
  // @@protoc_insertion_point(field_set:RemoveShape.shapeID)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RemoveShape_2eproto__INCLUDED
