// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomListResp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RoomListResp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* RoomListResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RoomListResp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_RoomListResp_2eproto() {
  protobuf_AddDesc_RoomListResp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RoomListResp.proto");
  GOOGLE_CHECK(file != NULL);
  RoomListResp_descriptor_ = file->message_type(0);
  static const int RoomListResp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomListResp, room_list_),
  };
  RoomListResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RoomListResp_descriptor_,
      RoomListResp::default_instance_,
      RoomListResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomListResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomListResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RoomListResp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RoomListResp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RoomListResp_descriptor_, &RoomListResp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_RoomListResp_2eproto() {
  delete RoomListResp::default_instance_;
  delete RoomListResp_reflection_;
}

void protobuf_AddDesc_RoomListResp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022RoomListResp.proto\"!\n\014RoomListResp\022\021\n\t"
    "room_list\030\001 \003(\t", 55);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RoomListResp.proto", &protobuf_RegisterTypes);
  RoomListResp::default_instance_ = new RoomListResp();
  RoomListResp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RoomListResp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RoomListResp_2eproto {
  StaticDescriptorInitializer_RoomListResp_2eproto() {
    protobuf_AddDesc_RoomListResp_2eproto();
  }
} static_descriptor_initializer_RoomListResp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int RoomListResp::kRoomListFieldNumber;
#endif  // !_MSC_VER

RoomListResp::RoomListResp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RoomListResp)
}

void RoomListResp::InitAsDefaultInstance() {
}

RoomListResp::RoomListResp(const RoomListResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:RoomListResp)
}

void RoomListResp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RoomListResp::~RoomListResp() {
  // @@protoc_insertion_point(destructor:RoomListResp)
  SharedDtor();
}

void RoomListResp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RoomListResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RoomListResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RoomListResp_descriptor_;
}

const RoomListResp& RoomListResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_RoomListResp_2eproto();
  return *default_instance_;
}

RoomListResp* RoomListResp::default_instance_ = NULL;

RoomListResp* RoomListResp::New() const {
  return new RoomListResp;
}

void RoomListResp::Clear() {
  room_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RoomListResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RoomListResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string room_list = 1;
      case 1: {
        if (tag == 10) {
         parse_room_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_room_list()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->room_list(this->room_list_size() - 1).data(),
            this->room_list(this->room_list_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "room_list");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_room_list;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RoomListResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RoomListResp)
  return false;
#undef DO_
}

void RoomListResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RoomListResp)
  // repeated string room_list = 1;
  for (int i = 0; i < this->room_list_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->room_list(i).data(), this->room_list(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "room_list");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->room_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:RoomListResp)
}

::google::protobuf::uint8* RoomListResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RoomListResp)
  // repeated string room_list = 1;
  for (int i = 0; i < this->room_list_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->room_list(i).data(), this->room_list(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "room_list");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->room_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RoomListResp)
  return target;
}

int RoomListResp::ByteSize() const {
  int total_size = 0;

  // repeated string room_list = 1;
  total_size += 1 * this->room_list_size();
  for (int i = 0; i < this->room_list_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->room_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RoomListResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RoomListResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RoomListResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RoomListResp::MergeFrom(const RoomListResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  room_list_.MergeFrom(from.room_list_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RoomListResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RoomListResp::CopyFrom(const RoomListResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoomListResp::IsInitialized() const {

  return true;
}

void RoomListResp::Swap(RoomListResp* other) {
  if (other != this) {
    room_list_.Swap(&other->room_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RoomListResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RoomListResp_descriptor_;
  metadata.reflection = RoomListResp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
